name: Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: AlexMeuer/turbo-pnpm-setup-action@v1

      - name: Build project
        run: pnpm run --filter=@repo/tauri build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files-web
          path: ./apps/tauri/dist

  deploy:
    name: Deploy Web
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files-web
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
